server {
    listen 80;
    server_name _;

    root /var/www/app/public;
    index index.php index.html index.htm;

    charset utf-8;
    client_max_body_size 500M;

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Ignore common files
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass backend:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Cache images
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # Cache CSS & JS
    location ~* \.(css|js)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    error_page 404 /index.php;
}